import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryButton from "../components/PrimaryButton";
import Flex from "../components/Flex";
import TextInput from "../components/TextInput";
import SearchIcon from "../public/search.svg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex className={"px-8 flex-col"}>
        <h1 className="text-5xl font-bold pt-40">
          Buy anything you need for your business.<br></br>From the Philippines.
        </h1>
        <Flex className={"pt-8"}>
          <label className={"relative block w-full"}>
            <span
              className={"absolute inset-y-0 left-0 flex items-center pl-2"}
            >
              <Image src={SearchIcon} />
            </span>
            <TextInput placeholder="Cement, PC monitors, PVC, etc..." />
          </label>
          <PrimaryButton>Search</PrimaryButton>
        </Flex>
      </Flex>
    </div>
  );
};

export default Home;
